name: movie_texo
description: "Movie list application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #PATTERNS
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  get_it: ^7.6.0
  http: 1.1.2

  #UI
  flutter_slider_drawer: ^2.1.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  build_runner: ^2.4.5
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true